apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
   name: debug
   project: roboshop
spec:
  containers:
  - name: nginx
    image: mahicharan/debug:v1
    imagePullPolicy: Always
    