apiVersion: v1
kind: ConfigMap
metadata:
 name: shipping
 namespace: roboshop
data:
 CART_ENDPOINT: "cart:8080"
 DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these are replica set labels
  labels:
    component: shipping
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: shipping
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: mahicharan/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 3
          periodSeconds: 15
---
#service
apiVersion: v1
kind: Service
metadata:
 name: shipping
 namespace: roboshop
spec:
  selector:
   component: shipping
   project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

 