apiVersion: v1
kind: ConfigMap
metadata:
 name: mysql
 namespace: roboshop
data:
 my.cnf: |
  [mysqld]
  innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these are replica set labels
  labels:
    component: mysql
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: mysql
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: mahicharan/mysql:v1
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        volumeMounts:
        - name: mysql-conf
          mountpath: /etc/mysql/conf.d/my.cnf
          subpath: my.cnf
      volumes:
       - name: mysql-conf
         configMap:
           name: mysql


---
#service
apiVersion: v1
kind: Service
metadata:
 name: mysql
 namespace: roboshop
spec:
  selector:
   component: mysql
   project: roboshop
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

 