apiVersion: v1
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
data:
 MONGO: "true"
 REDIS_URL: "redis://redis:6379"
 MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespcae: roboshop
  # these are replica set labels
  labels:
    component: user
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: user
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
    spec:
      containers:
      - name: user
        image: tmahicharan/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
          name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
---
#service
apiVersion: v1
kind: Service
metadata:
 name: user
 namespace: roboshop
spec:
  selector:
   component: user
   project: roboshop
   env: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

 